server:
  port: 8082

spring:
  profiles:
    active: qa
---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: new-password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
welcome:
  message: Some Configuration Data

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcbappqa
    username: root
    password: new-password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: qa
welcome:
  message: Some Configuration Data

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcbappprod
    username: root
    password: new-password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: prod
welcome:
  message: Some Configuration Data
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"


